<?php
// UTF-8
// Déclaration des icones utilisées par l'application

$Icones['home'] = 'house.png';
$Icones['previous'] = 'resultset_previous.png';
$Icones['text'] = 'page_white_text.png';
$Icones['information'] = 'information.png';
$Icones['tip'] = 'lightbulb.png';
$Icones['menu_open'] = 'bullet_go.png';
$Icones['menu_option'] = 'bullet_green.png';
$Icones['email'] = 'email.png';
$Icones['help'] = 'help.png';
$Icones['internet_oui'] = 'world_add.png';
$Icones['internet_non'] = 'world_delete.png';
$Icones['fiche_validee'] = 'tick.png';
$Icones['fiche_non_validee'] = 'cross.png';
$Icones['fiche_internet'] = 'world_go.png';
$Icones['fiche_edition'] = 'page_white_edit.png';
$Icones['fiche_controle'] = 'page_refresh.png';
$Icones['page_haut'] = 'bullet_arrow_top.png';
$Icones['ajouter'] = 'page_add.png';
$Icones['couple_donne'] = 'arrow_turn_right2.png';
$Icones['arbre_asc'] = 'Arbre_Asc.png';
$Icones['arbre_desc'] = 'Arbre_Desc.png';
$Icones['gedcom'] = 'gedcom.png';
$Icones['note'] = 'attach.png';
$Icones['oeil'] = 'eye.png';
$Icones['arrange'] = 'arrow_switch.png';
$Icones['warning'] = 'error.png';
$Icones['obligatoire'] = 'wand.png';
$Icones['calendrier'] = 'calendar.png';
$Icones['ajout'] = 'add.png';
$Icones['ajout_URL'] = 'link_add.png';
$Icones['va_URL'] = 'link_go.png';
$Icones['fiche_fam'] = 'group_gear.png';
$Icones['images'] = 'images.png';
$Icones['loupe'] = 'magnifier.png';
$Icones['localisation'] = 'map.png';
$Icones['copie_calend'] = 'calendar_edit.png';
$Icones['anniv_mar'] = 'heart.png';
$Icones['anniv_dec'] = 'bell.png';
$Icones['anniv_nai'] = 'cake.png';
$Icones['ligne_vert'] = 'line_ud.png';
$Icones['image_defaut'] = 'arrow_in.png';
$Icones['drapeau_orange'] = 'flag_orange.png';
$Icones['drapeau_vert'] = 'flag_green.png';
$Icones['stop'] = 'stop.png';
$Icones['calculette'] = 'calculator.png';
$Icones['efface'] = 'efface.png';
$Icones['homme'] = 'male.png';
$Icones['femme'] = 'female.png';
$Icones['carte_france'] = 'carteFrance.png';
$Icones['commentaire'] = 'comment.png';
$Icones['ajout_rapide'] = 'lightning_add.png';
$Icones['etoile'] = 'star.png';
$Icones['contribuer'] = 'contribuer.png';
$Icones['manuel'] = 'book_open.png';
$Icones['page'] = 'page_white_get.png';
$Icones['2personnes'] = 'homonymes.png';
$Icones['arbre_ascP'] = 'Arbre_Asc_Plus.png';
$Icones['GeneGraphe'] = 'GeneGraphe.png';
$Icones['PDF'] = 'page_white_acrobat.png';
$Icones['decujus'] = 'arrow_divide.png';
$Icones['supp'] = 'delete.png';         			// nouveau 4.0
$Icones['majuscule'] = 'text_uppercase.png';		// "
$Icones['moins'] = 'bullet_toggle_moins2.png';		// "
$Icones['plus'] = 'bullet_toggle_plus2.png';		// "
$Icones['copier'] = 'pencil_go.png';				// "
$Icones['fleche_haut'] = 'bullet_arrow_up.png';		// "
$Icones['time_line'] = 'date_magnify.png';			// nouveau 4.2
$Icones['tag_bleu'] = 'tag_blue.png';				// "
$Icones['tag_vert'] = 'tag_green.png';				// "
$Icones['tag_orange'] = 'tag_orange.png';			// "
$Icones['tag_rose'] = 'tag_pink.png';				// "
$Icones['tag_violet'] = 'tag_purple.png';			// "
$Icones['tag_rouge'] = 'tag_red.png';				// "
$Icones['tag_jaune'] = 'tag_yellow.png';			// "
$Icones['map_go'] = 'map_go.png';					// "
$Icones['groupe'] = 'group_go.png';					// nouveau 4.3
$Icones['aujourdhui'] = 'calendar_view_day.png';	// "
$Icones['drapeau_rouge'] = 'flag_red.png';			// nouveau 4.4 - 5
$Icones['exp_tab'] = 'table_save.png';				// nouveau > 5.0.1
$Icones['cancel'] = 'cancel.png';
$Icones['conversion'] = 'arrow_refresh.png';
$Icones['chercher'] = 'page_white_find.png';
$Icones['accepter'] = 'accept.png';
$Icones['fleche_bas'] = 'arrow_down.png';
$Icones['supprimer'] = 'application_form_delete.png';
$Icones['connecter'] = 'application_key.png';		// nouveau > 6.2
$Icones['deconnecter'] = 'application_go.png';
$Icones['vue_pers'] = 'vue_pers.png';		
$Icones['first'] = 'resultset_first.png';	
$Icones['last'] = 'resultset_last.png';		
$Icones['next'] = 'resultset_next.png';		
$Icones['dernier_ajoute'] = 'time_add.png';	
$Icones['ajout_multiple'] = 'folder_add.png';
$Icones['liste_nom'] = 'folder_user.png';	
$Images['bar_on'] = 'bar_on.gif';			
$Images['clear'] = 'clear.gif';				
$Images['fond_metal'] = 'pascaline3.jpg';	
$Icones['asc_conj'] = 'arrow_out.png';
$Icones['chercher_plus'] = 'page_white_wrench.png';
?>